AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**/*
    - db/schema.rb
    - bin/*
    - config/initializers/core_ext.rb
    - app/helpers/application_helper.rb

Encoding:
  Enabled: false
Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
LineLength:
  Description: 'Limit lines to 80 characters. For now disabled'
  Enabled: false
AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false
CyclomaticComplexity:
  Max: 10
MethodLength:
  Max: 15
TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  Enabled: false
